ALTER TABLE "request_for_pda" ALTER COLUMN eta TYPE date USING eta::date;--> statement-breakpoint
ALTER TABLE "buy_container" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "buy_container" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "buy_vessel" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "buy_vessel" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "container_inland_services" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "container_inland_services" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "dangerous_cargo_services" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "dangerous_cargo_services" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "heavy_lift" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "heavy_lift" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "handling_stevedoring_storage" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "handling_stevedoring_storage" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "international_trading" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "international_trading" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "less_than_container_load" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "less_than_container_load" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "oversized_container" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "oversized_container" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "project_cargo_services" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "project_cargo_services" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "rent_container" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "rent_container" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "rent_vessel" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "rent_vessel" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "roll_on_off" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "roll_on_off" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "ship_maintenance" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "ship_maintenance" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "ship_management" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "ship_management" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "sign_crew_members" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "sign_crew_members" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "special_services" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "special_services" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "standard_container" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "standard_container" ADD COLUMN "additional_phone_number" text;--> statement-breakpoint
ALTER TABLE "transfer_spare_parts" ADD COLUMN "additional_email" text;--> statement-breakpoint
ALTER TABLE "transfer_spare_parts" ADD COLUMN "additional_phone_number" text;