-- Safely convert location column to jsonb
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "location";
ALTER TABLE "handling_stevedoring_storage" ADD COLUMN "location" jsonb;
ALTER TABLE "handling_stevedoring_storage" ADD COLUMN "commodities" jsonb NOT NULL;
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "detailed";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "dangerous";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "oversized";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "temperature";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "container_type";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "container_number";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "container_weight";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "length";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "width";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "height";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "weight";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "file";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "additional_information";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "handling";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "loading";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "discharging";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "lashing";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "unlashing";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "safekeeping_before";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "safekeeping_after";
ALTER TABLE "handling_stevedoring_storage" DROP COLUMN IF EXISTS "temporary_storage"; 